// examples/react-basic/src/components/Sidebar.tsx
import { useEffect, useState } from 'react';
import { Doc } from '@blocksuite/store';
import { useEditor } from '../editor/context';

const Sidebar = () => {
  const { collection, editor } = useEditor()!;
  const [docs, setDocs] = useState<Doc[]>([]);

  useEffect(() => {
    if (!collection || !editor) return;
    const updateDocs = () => {
      const docs = [...collection.docs.values()].map(blocks => blocks.getDoc());
      setDocs(docs);
    };
    updateDocs();

    const disposable = [
      collection.slots.docUpdated.on(updateDocs),
      editor.slots.docLinkClicked.on(updateDocs),
    ];

    return () => disposable.forEach(d => d.dispose());
  }, [collection, editor]);

  return (
    <div className="sidebar">
      <div className="header">All Docs</div>
      <div className="doc-list">
        {docs.map(doc => (
          <div
            className={`doc-item ${editor?.doc === doc ? 'active' : ''}`}
            key={doc.id}
            onClick={() => {
              if (editor) editor.doc = doc;
              const docs = [...collection.docs.values()].map(blocks =>
                blocks.getDoc()
              );
              setDocs(docs);
            }}
          >
            {doc.meta?.title || 'Untitled'}
          </div>
        ))}
      </div>
    </div>
  );
};

export default Sidebar;

// examples/vue-basic/src/components/Sidebar.vue
<template>
  <div class="sidebar">
    <div class="header">All Docs</div>
    <div class="doc-list">
      <div
        v-for="doc in docs"
        :key="doc.id"
        :class="{ 'doc-item': true, active: editor?.doc === doc }"
        @click="selectDoc(doc as Doc)"
      >
        {{ doc.meta?.title || 'Untitled' }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { inject, ref } from 'vue';
import { AppState } from './EditorProvider.vue';
import { Doc } from '@blocksuite/store';

const { editor, collection } = inject<AppState>('appState')!;
const docs = ref<Doc[]>(
  [...collection.docs.values()].map(blocks => blocks.getDoc())
);

const updateDocs = () =>
  (docs.value = [...collection.docs.values()].map(blocks => blocks.getDoc()));

collection.slots.docUpdated.on(updateDocs);
editor.slots.docLinkClicked.on(updateDocs);

const selectDoc = (doc: Doc) => {
  editor.doc = doc;
  updateDocs();
};
</script>
