// examples/react-websocket/src/client/App.tsx
import { EditorProvider } from './components/EditorProvider.js';
import Sidebar from './components/Sidebar.js';
import TopBar from './components/TopBar.js';
import EditorContainer from './components/EditorContainer.js';
import './index.css';

function App() {
  return (
    <EditorProvider>
      <div className="app">
        <Sidebar />
        <div className="main-content">
          <TopBar />
          <EditorContainer />
        </div>
      </div>
    </EditorProvider>
  );
}

export default App;

// examples/vue-basic/src/App.vue
<template>
  <EditorProvider>
    <div class="app">
      <Sidebar />
      <div class="main-content">
        <TopBar />
        <EditorContainer />
      </div>
    </div>
  </EditorProvider>
</template>

<script setup>
import EditorProvider from './components/EditorProvider.vue';
import Sidebar from './components/Sidebar.vue';
import TopBar from './components/TopBar.vue';
import EditorContainer from './components/EditorContainer.vue';
import './index.css';
</script>
