// examples/solid-basic/src/components/EditorContainer.tsx
import { onMount } from 'solid-js';
import { useEditor } from './EditorProvider';

export function EditorContainer() {
  let editorContainerRef: HTMLDivElement | undefined;

  const { editor } = useEditor()!;

  onMount(() => {
    if (editorContainerRef) {
      editorContainerRef.appendChild(editor);
    }
  });

  return <div class="editor-container" ref={editorContainerRef}></div>;
}

// examples/react-basic/src/components/EditorContainer.tsx
import { useEffect, useRef } from 'react';
import { useEditor } from '../editor/context';

const EditorContainer = () => {
  const { editor } = useEditor()!;

  const editorContainerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (editorContainerRef.current && editor) {
      editorContainerRef.current.innerHTML = '';
      editorContainerRef.current.appendChild(editor);
    }
  }, [editor]);

  return <div className="editor-container" ref={editorContainerRef}></div>;
};

export default EditorContainer;
