// examples/preact-basic/src/components/EditorProvider.tsx
import Preact from 'preact';
import { initEditor } from '../editor/editor';
import { EditorContext } from '../editor/context';

export const EditorProvider = ({ children }: { children: Preact.VNode }) => {
  const { editor, collection } = initEditor();

  return (
    <EditorContext.Provider value={{ editor, collection }}>
      {children}
    </EditorContext.Provider>
  );
};

// examples/solid-basic/src/components/EditorProvider.tsx
import { JSX, createContext, useContext } from 'solid-js';
import { initEditor, AppState } from '../editor/editor';

const EditorContext = createContext<AppState>();

export function EditorProvider(props: { children: JSX.Element }) {
  const appState = initEditor();

  return (
    <EditorContext.Provider value={appState}>
      {props.children}
    </EditorContext.Provider>
  );
}

export function useEditor() {
  return useContext(EditorContext);
}
